import asyncio
import random
from datetime import datetime, timezone

# this log messages generated by AI
ERROR_MESSAGES = [
    "Hardware fault detected on primary bus",
    "Sensor communication timeout",
    "Memory parity error in subsystem",
    "Unexpected watchdog reset",
    "Payload controller unresponsive",
]

SAFE_MESSAGES = [
    "Heartbeat timeout from peer satellite",
    "Detected ERROR state on peer satellite",
    "Constellation safety protocol triggered",
    "Peer satellite communication lost",
]

async def event_engine(satellites, broadcast):
    while True:
        await asyncio.sleep(random.uniform(15.0, 30.0))

        eligible = [s for s in satellites if s.state() in ["new", "init", "orbit", "run"]]

        if not eligible:
            continue

        sat = random.choice(eligible)
        timestamp = datetime.now(timezone.utc).strftime("%H:%M:%S")

        # 60/100 -> ERROR
        # 40/100 -> SAFE chance
        if random.random() < 0.6:
            event_cmd = "ERROR"
            message = random.choice(ERROR_MESSAGES)
            log_level = "CRITICAL"
        else:
            event_cmd = "SAFE"
            message = random.choice(SAFE_MESSAGES)
            log_level = "WARNING"

        success = sat.process_cmd(event_cmd)
        if not success:
            continue

        # log
        await broadcast({
            "type": "LOG",
            "sender": sat.name,
            "level": log_level,
            "message": message,
            "timestamp": timestamp
        })

        # broadcast state change
        await broadcast({
            "type": "SATELLITE_STATE_UPDATE",
            "satellite_id": sat.id,
            "satellite_name": sat.name,
            "new_state": sat.state(),
            "last_message": sat.last_message,
            "timestamp": timestamp
        })

        await broadcast({
            "type": "LOG",
            "sender": "System",
            "level": "INFO",
            "message": f"Satellite {sat.name} state changed to {sat.state()}",
            "timestamp": timestamp
        })
